# GENERATED FILE. DO NOT EDIT.
#
# Source of truth: claude-blog's vi_profile.py (VI_TELLS).
# Regenerate:      run sync_vi_tells.py with --write in the claude-blog repository.
# A hand edit here is detected by tests/test_vi_tells_sync.py in both
# repositories and is overwritten by the next --write.
# body-sha256: 1ff3ab78a8d976747e55c832a0e706db463f5397e379f54b474de61446763249
# ---- BEGIN GENERATED BODY (sha256 covers everything below this line) ----
"""Vietnamese tell table for content_humanize.py --lang vi. Generated."""

# (regex, replacement, label): applied in order, case-insensitive.
VI_REWRITES: tuple[tuple[str, str, str], ...] = (
    ("trong\\s+thời\\s+đại\\s+số\\s+hóa(?:\\s+(?:ngày\\s+nay|hiện\\s+nay))?\\s*", "hiện nay ", "thoi-dai-so-hoa"),
    ("không\\s+thể\\s+phủ\\s+nhận\\s+rằng\\s*", "", "khong-the-phu-nhan-rang"),
    ("đóng\\s+vai\\s+trò\\s+vô\\s+cùng\\s+quan\\s+trọng", "rất quan trọng", "vai-tro-vo-cung-quan-trong"),
    ("mang\\s+lại\\s+nhiều\\s+lợi\\s+ích\\s+thiết\\s+thực", "hữu ích", "loi-ich-thiet-thuc"),
    ("giúp\\s+bạn\\s+dễ\\s+dàng\\s+hơn\\s+bao\\s+giờ\\s+hết", "giúp bạn dễ dàng hơn", "de-dang-hon-bao-gio-het"),
    ("chúc\\s+(?:các\\s+)?bạn\\s+thành\\s+công[ \\t]*[.!]*[ \\t]*", "", "chuc-ban-thanh-cong"),
    ("điều\\s+này\\s+cho\\s+thấy\\s+rằng", "điều này cho thấy", "dieu-nay-cho-thay-rang"),
    ("có\\s+thể\\s+nói\\s+rằng\\s*", "", "co-the-noi-rang"),
    ("một\\s+trong\\s+những\\s+yếu\\s+tố\\s+quan\\s+trọng\\s+nhất", "một yếu tố quan trọng", "yeu-to-quan-trong-nhat"),
    ("với\\s+sự\\s+phát\\s+triển\\s+mạnh\\s+mẽ\\s+của", "nhờ sự phát triển của", "phat-trien-manh-me"),
    ("đáp\\s+ứng\\s+nhu\\s+cầu\\s+ngày\\s+càng\\s+cao", "đáp ứng nhu cầu ngày càng lớn", "nhu-cau-ngay-cang-cao"),
    ("đã\\s+và\\s+đang\\s+", "đang ", "da-va-dang"),
    ("ngày\\s+càng\\s+trở\\s+nên\\s+phổ\\s+biến", "ngày càng phổ biến", "f-ngay-cang-tro-nen"),
    ("hy\\s+vọng\\s+(?:rằng\\s+)?bài\\s+viết\\s+(?:này\\s+)?(?:sẽ\\s+|đã\\s+)?(?:hữu\\s+ích|giúp\\s+ích|giúp\\s+được|mang\\s+đến)[^.!?]*[.!?]?[ \\t]*", "", "f-hy-vong-bai-viet"),
)

# (id, tier, text, regex, label): the full tell list, for reference and
# for detection-only callers. Not used by the rewrite path.
VI_TELLS_DATA: tuple[tuple[str, str, str | None, str | None, str], ...] = (
    ("thoi-dai-so-hoa", "phrase", "trong thời đại số hóa", None, "Mở bài sáo rỗng"),
    ("khong-the-phu-nhan-rang", "phrase", "không thể phủ nhận rằng", None, "Khẳng định rỗng"),
    ("vai-tro-vo-cung-quan-trong", "phrase", "đóng vai trò vô cùng quan trọng", None, "Cụm mòn"),
    ("loi-ich-thiet-thuc", "phrase", "mang lại nhiều lợi ích thiết thực", None, "Hứa hẹn mơ hồ"),
    ("de-dang-hon-bao-gio-het", "phrase", "giúp bạn dễ dàng hơn bao giờ hết", None, "Hứa hẹn mơ hồ"),
    ("hy-vong-da-mang-den", "phrase", "hy vọng bài viết đã mang đến", None, "Kết bài sáo rỗng"),
    ("hy-vong-da-giup", "phrase", "hy vọng bài viết này đã giúp", None, "Kết bài sáo rỗng"),
    ("chuc-ban-thanh-cong", "phrase", "chúc bạn thành công", None, "Kết bài sáo rỗng"),
    ("dieu-nay-cho-thay-rang", "phrase", "điều này cho thấy rằng", None, "Câu đệm"),
    ("co-the-noi-rang", "phrase", "có thể nói rằng", None, "Câu đệm"),
    ("yeu-to-quan-trong-nhat", "phrase", "một trong những yếu tố quan trọng nhất", None, "Cụm mòn"),
    ("phat-trien-manh-me", "phrase", "với sự phát triển mạnh mẽ của", None, "Mở bài sáo rỗng"),
    ("nhu-cau-ngay-cang-cao", "phrase", "đáp ứng nhu cầu ngày càng cao", None, "Cụm mòn"),
    ("khong-co-gi-ngac-nhien", "phrase", "không có gì ngạc nhiên khi", None, "Câu đệm"),
    ("hay-cung-tim-hieu", "phrase", "hãy cùng tìm hiểu", None, "Dẫn dắt thừa"),
    ("bai-viet-nay-se-giup-ban", "phrase", "bài viết này sẽ giúp bạn", None, "Meta thừa"),
    ("hy-vong-nhung-chia-se", "phrase", "hy vọng những chia sẻ trên", None, "Kết bài sáo rỗng"),
    ("vo-cung-quan-trong", "trigger", "vô cùng quan trọng", None, "Cụm mòn"),
    ("dong-vai-tro-quan-trong", "trigger", "đóng vai trò quan trọng", None, "Cụm mòn"),
    ("khong-the-phu-nhan", "trigger", "không thể phủ nhận", None, "Khẳng định rỗng"),
    ("de-dang-hon-bao-gio-het-trigger", "trigger", "dễ dàng hơn bao giờ hết", None, "Hứa hẹn mơ hồ"),
    ("vai-tro-then-chot", "trigger", "vai trò then chốt", None, "Cụm mòn"),
    ("mot-cach-toan-dien", "trigger", "một cách toàn diện", None, "Cụm mòn"),
    ("het-suc-quan-trong", "trigger", "hết sức quan trọng", None, "Cụm mòn"),
    ("chia-khoa-thanh-cong", "trigger", "chìa khóa thành công", None, "Cụm mòn"),
    ("buoc-tien-quan-trong", "trigger", "bước tiến quan trọng", None, "Cụm mòn"),
    ("yeu-to-then-chot", "trigger", "yếu tố then chốt", None, "Cụm mòn"),
    ("xu-huong-tat-yeu", "trigger", "xu hướng tất yếu", None, "Cụm mòn"),
    ("khong-ngung-phat-trien", "trigger", "không ngừng phát triển", None, "Cụm mòn"),
    ("dong-gop-to-lon", "trigger", "đóng góp to lớn", None, "Cụm mòn"),
    ("vai-tro-khong-the-thay-the", "trigger", "vai trò không thể thay thế", None, "Cụm mòn"),
    ("giai-phap-toi-uu", "trigger", "giải pháp tối ưu", None, "Cụm mòn"),
    ("trai-nghiem-tuyet-voi", "trigger", "trải nghiệm tuyệt vời", None, "Cụm mòn"),
    ("buoc-ngoat-quan-trong", "trigger", "bước ngoặt quan trọng", None, "Cụm mòn"),
    ("tiem-nang-to-lon", "trigger", "tiềm năng to lớn", None, "Cụm mòn"),
    ("gia-tri-to-lon", "trigger", "giá trị to lớn", None, "Cụm mòn"),
    ("cot-moc-quan-trong", "trigger", "cột mốc quan trọng", None, "Cụm mòn"),
    ("da-va-dang", "advisory", "đã và đang", None, "Cụm dễ thừa"),
    ("adv-boi-canh-hien-nay", "advisory", "trong bối cảnh hiện nay", None, "Cụm dễ thừa"),
    ("adv-vai-tro-quan-trong", "advisory", "vai trò quan trọng", None, "Cụm dễ thừa"),
    ("adv-ngay-cang-pho-bien", "advisory", "ngày càng phổ biến", None, "Cụm dễ thừa"),
    ("adv-ngay-cang-tang", "advisory", "ngày càng tăng", None, "Cụm dễ thừa"),
    ("adv-khong-the-thieu", "advisory", "không thể thiếu", None, "Cụm dễ thừa"),
    ("adv-hieu-qua-cao", "advisory", "hiệu quả cao", None, "Cụm dễ thừa"),
    ("adv-chat-luong-cao", "advisory", "chất lượng cao", None, "Cụm dễ thừa"),
    ("adv-nhu-cau-ngay-cang-cao", "advisory", "nhu cầu ngày càng cao", None, "Cụm dễ thừa"),
    ("adv-xu-huong-phat-trien", "advisory", "xu hướng phát triển", None, "Cụm dễ thừa"),
    ("f-mo-bai-thoi-dai", "formula", None, "trong\\s+(?:thế\\s+giới|thời\\s+đại|bối\\s+cảnh)\\s+(?:ngày\\s+nay|hiện\\s+nay|số\\s+ho[áa]|công\\s+nghệ\\s+số|4\\.0)", "Mở bài sáo rỗng"),
    ("f-khong-the-phu-nhan", "formula", None, "không\\s+thể\\s+phủ\\s+nhận\\s+(?:rằng|là)", "Khẳng định rỗng"),
    ("f-dieu-quan-trong", "formula", None, "điều\\s+(?:quan\\s+trọng|đáng\\s+lưu\\s+ý)\\s+(?:cần\\s+)?(?:lưu\\s+ý|nhớ|biết)\\s+là", "Câu đệm"),
    ("f-hay-cung", "formula", None, "hãy\\s+cùng\\s+(?:đi\\s+sâu|tìm\\s+hiểu|khám\\s+phá|điểm\\s+qua)", "Dẫn dắt thừa"),
    ("f-tom-lai", "formula", None, "(?:tóm\\s+lại|nhìn\\s+chung)\\s*,?\\s*(?:có\\s+thể\\s+thấy|chúng\\s+ta\\s+có\\s+thể\\s+thấy)", "Kết bài sáo rỗng"),
    ("f-vai-tro-quan-trong", "formula", None, "đóng\\s+(?:một\\s+)?vai\\s+trò\\s+(?:vô\\s+cùng\\s+)?quan\\s+trọng", "Cụm mòn"),
    ("f-ngay-cang-tro-nen", "formula", None, "ngày\\s+càng\\s+trở\\s+nên\\s+(?:phổ\\s+biến|quan\\s+trọng|cần\\s+thiết)", "Cụm mòn"),
    ("f-yeu-to-then-chot", "formula", None, "là\\s+một\\s+trong\\s+những\\s+yếu\\s+tố\\s+(?:then\\s+chốt|quan\\s+trọng\\s+nhất)", "Cụm mòn"),
    ("f-giup-toi-uu", "formula", None, "giúp\\s+(?:bạn\\s+)?(?:tối\\s+ưu\\s+ho[áa]|nâng\\s+cao|cải\\s+thiện)\\s+(?:một\\s+cách\\s+)?(?:hiệu\\s+quả|đáng\\s+kể|tối\\s+đa)", "Hứa hẹn mơ hồ"),
    ("f-trong-bai-viet-nay", "formula", None, "trong\\s+bài\\s+viết\\s+(?:này|dưới\\s+đây)\\s*,?\\s*(?:chúng\\s+ta|chúng\\s+tôi|tôi)\\s+sẽ", "Meta thừa"),
    ("f-hy-vong-bai-viet", "formula", None, "hy\\s+vọng\\s+(?:rằng\\s+)?bài\\s+viết\\s+(?:này\\s+)?(?:sẽ\\s+|đã\\s+)?(?:hữu\\s+ích|giúp\\s+ích|giúp\\s+được|mang\\s+đến)", "Kết bài sáo rỗng"),
    ("f-phat-trien-cong-nghe", "formula", None, "với\\s+sự\\s+phát\\s+triển\\s+(?:không\\s+ngừng\\s+)?của\\s+(?:công\\s+nghệ|internet)", "Mở bài sáo rỗng"),
    ("r-hy-vong-bai-viet-nay", "residue", None, "hy\\s+vọng\\s+bài\\s+viết\\s+này", "Chatbot residue"),
    ("r-duoi-day-la", "residue", None, "^\\s*dưới\\s+đây\\s+là\\b", "Chatbot residue"),
    ("r-chac-chan-roi", "residue", None, "chắc\\s+chắn\\s+rồi", "Chatbot residue"),
    ("r-rat-vui-duoc-ho-tro", "residue", None, "rất\\s+vui\\s+được\\s+hỗ\\s+trợ\\s+bạn", "Chatbot residue"),
    ("r-ban-co-muon-toi", "residue", None, "bạn\\s+có\\s+muốn\\s+(?:tôi|mình)", "Chatbot residue"),
    ("r-hay-cho-toi-biet", "residue", None, "hãy\\s+cho\\s+tôi\\s+biết\\s+nếu\\s+bạn", "Chatbot residue"),
    ("c-doc-lai-cau-tren", "closer", None, "hãy\\s+đọc\\s+lại\\s+câu\\s+trên", "Câu chốt sáo rỗng"),
    ("c-mau-chot", "closer", None, "đó\\s+(?:(?:mới|chính|thực\\s+sự|thật\\s+sự)\\s+)*là\\s+mấu\\s+chốt", "Câu chốt sáo rỗng"),
    ("c-cot-loi", "closer", None, "đó\\s+(?:(?:mới|chính|thực\\s+sự|thật\\s+sự)\\s+)*là\\s+(?:điều|vấn\\s+đề)\\s+(?:cốt\\s+lõi|quan\\s+trọng)", "Câu chốt sáo rỗng"),
    ("c-tham", "closer", None, "hãy\\s+để\\s+điều\\s+đó\\s+thấm", "Câu chốt sáo rỗng"),
    ("c-nam-o-do", "closer", None, "vấn\\s+đề\\s+(?:chính\\s+)?nằm\\s+ở\\s+đó", "Câu chốt sáo rỗng"),
    ("c-ly-do", "closer", None, "và\\s+đó\\s+là\\s+lý\\s+do", "Câu chốt sáo rỗng"),
)
